name: ACTOM-Advection
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python==3.8
  - tqdm==4.63.0
  - numpy==1.22.0
  - pandas==1.3.5
  - scipy==1.7.3
  - future==0.18.2 
  - matplotlib==3.3.1
  - imageio==2.13.5
  - netCDF4==1.5.7
  - scikit-learn==1.0.2
  - xarray==0.20.2
  - Bottleneck==1.3.2
  - gmsh==4.8.4
  - FiPy==3.4.2.1
  - pyproj==3.1.0
  - sphinx==4.2.0
  - sphinx-rtd-theme==1.0.0
